name: deplyment pipeline

on:
  push:
    branches:  [main] 

jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - uses: actions/setup-node@v4
         with:
           node-version: 19
       - name: install dependencies --no-audit --no-found --no-optional
         run: npm install
       - name: Lint
         run: npm run lint 
       - name: Test
         run: npm run test